<a href="https://colab.research.google.com/github/stemgene/Pytorch_training/blob/master/Fastai_style_transfer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/ZeweiChu/PyTorch-Course/blob/master/notebooks/

https://github.com/zhanghang1989/PyTorch-Multi-Style-Transfer

http://francescopochetti.com/style-transfer-with-fast-ai-and-pytorch/

## 什么是PyTorch?

PyTorch是一个基于Python的科学计算库，它有以下特点:

* 类似于NumPy，但是它可以使用GPU
* 可以用它定义深度学习模型，可以灵活地进行深度学习模型的训练和使用

### Tensors

Tensor类似与NumPy的ndarray，唯一的区别是Tensor可以在GPU上加速运算。

In [0]:
from __future__ import print_function
import torch

构造一个未初始化的5x3矩阵:  未初始化: very large or small

In [0]:
x = torch.empty(5, 3)
x

tensor([[4.9657e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


构建一个随机初始化的矩阵:

In [0]:
x = torch.rand(5, 3)
x

tensor([[0.4527, 0.3758, 0.5167],
        [0.7446, 0.2886, 0.4652],
        [0.5858, 0.5637, 0.1437],
        [0.9325, 0.1720, 0.8560],
        [0.2352, 0.0334, 0.4608]])

构建一个全部为0，类型为long的矩阵(long int):

In [0]:
x = torch.zeros(5,3)
x.dtype

torch.float32

In [0]:
x = torch.zeros(5,3, dtype=torch.long)
x.dtype

torch.int64

In [0]:
x = torch.zeros(5,3).long()
x.dtype

torch.int64

从数据直接直接构建tensor:

In [0]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

也可以从一个已有的tensor构建一个tensor。这些方法会重用原来tensor的特征，例如，数据类型，除非提供新的数据。

In [0]:
x = x.new_ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [0]:
x = x.new_ones(5,3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [0]:
x = torch.rand_like(x, dtype=torch.float)
x

tensor([[0.8707, 0.1382, 0.2775],
        [0.9789, 0.8968, 0.9993],
        [0.6050, 0.7385, 0.6711],
        [0.2902, 0.9769, 0.0698],
        [0.4830, 0.7638, 0.6863]])

In [0]:
dir(x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__se

得到tensor的形状:

In [0]:
x.shape

torch.Size([5, 3])

In [0]:
#注意:``torch.Size`` 返回的是一个tuple
x.size()

torch.Size([5, 3])

Resizing: 如果你希望resize/reshape一个tensor，可以使用torch.view：

In [0]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8) #the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有一个只有一个元素的tensor，使用.item()方法可以把里面的value变成Python数值。

In [0]:
x = torch.randn(1)
x.item()

0.8007168173789978

### Operations

有很多种tensor运算。我们先介绍加法运算。

In [0]:
y = torch.rand_like(x)
print(x+y)

tensor([[1.5322, 0.5965, 0.6609],
        [1.7503, 1.7752, 1.9653],
        [0.8923, 1.6527, 1.6047],
        [0.4350, 1.7578, 0.2323],
        [1.1993, 0.9583, 0.7724]])


另一种着加法的写法

In [0]:
torch.add(x,y)

tensor([[1.5322, 0.5965, 0.6609],
        [1.7503, 1.7752, 1.9653],
        [0.8923, 1.6527, 1.6047],
        [0.4350, 1.7578, 0.2323],
        [1.1993, 0.9583, 0.7724]])

把输出作为一个变量

In [0]:
result = torch.empty_like(x)
torch.add(x,y, out=result)
# result = x + y
result

tensor([[1.5322, 0.5965, 0.6609],
        [1.7503, 1.7752, 1.9653],
        [0.8923, 1.6527, 1.6047],
        [0.4350, 1.7578, 0.2323],
        [1.1993, 0.9583, 0.7724]])

in-place加法, all '_' means self operation

注意: 

任何in-place的运算都会以``_``结尾。 举例来说：``x.copy_(y)``, ``x.t_()``, 会改变 ``x``。

In [0]:
# adds x to y
y.add_(x)
y

tensor([[1.5322, 0.5965, 0.6609],
        [1.7503, 1.7752, 1.9653],
        [0.8923, 1.6527, 1.6047],
        [0.4350, 1.7578, 0.2323],
        [1.1993, 0.9583, 0.7724]])

更多阅读

各种Tensor operations, 包括transposing, indexing, slicing, mathematical operations, linear algebra, random numbers在 <https://pytorch.org/docs/torch>.

### Index

各种类似NumPy的indexing都可以在PyTorch tensor上面使用。

In [0]:
print(x[:, 1:])

tensor([[0.1382, 0.2775],
        [0.8968, 0.9993],
        [0.7385, 0.6711],
        [0.9769, 0.0698],
        [0.7638, 0.6863]])


## Numpy和Tensor之间的转化

在Torch Tensor和NumPy array之间相互转化非常容易。

Torch Tensor和NumPy array会共享内存，所以改变其中一项也会改变另一项。

把Torch Tensor转变成NumPy Array

In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


改变numpy array里面的值。 a and b change together

In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


把NumPy ndarray转成Torch Tensor

In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
使用.to方法，Tensor可以被移动到别的device上。

In [0]:
torch.cuda.is_available()

False

In [0]:
# Let us run this cell only if CUDA is available
# We will use "torch.device" objects to move tensors in and out of GPU
if torch.cuda.is_available():
  device = torch.device("cuda")              # a CUDA device object
  y = torch.ones_like(x, device=device)      # directly create a tensor on GPU
  x = x.to(device)                           # or just use strings '.to("CUDA")'
  z = x + y
  print(z)
  print(z.to('cpu', torch.double))           # '.to' can also change dtype together

If some tensor is GPU, it cannon be simply transfered to numpy or be shown, it should be transfered to CPU first.

In [0]:
y.to('cpu').data.numpy()
y.cpu().data.numpy()

set a whole model to CUDA

In [0]:
model = model.cuda()

## 热身: 用numpy实现两层神经网络
一个全连接ReLU神经网络，一个隐藏层，没有bias。用来从x预测y，使用L2 Loss。

* $h = W_1X + b_1$
* $a = max(0, h)$
* $y_{hat} = W_2a + b_2$

这一实现完全使用numpy来计算前向神经网络，loss，和反向传播。
- forward pass
- loss
- backward pass

numpy ndarray是一个普通的n维array。它不知道任何关于深度学习或者梯度(gradient)的知识，也不知道计算图(computation graph)，只是一种用来计算数学运算的数据结构。

In [0]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# randomly generate traning data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6
for it in range(500):
  #Forward pass
  h = x.dot(w1)  # N * H
  h_relu = np.maximum(h, 0) # N * H
  y_pred = h_relu.dot(w2)   # N * D_out

  # compute loss
  loss = np.square(y_pred - y).sum()
  print(it, loss)

  # Backward pass
  #compute the gradient
  grad_y_pred = 2.0 * (y_pred - y)
  grad_w2 = h_relu.T.dot(grad_y_pred)
  grad_h_relu = grad_y_pred.dot(w2.T)
  grad_h = grad_h_relu.copy()
  grad_h[h<0] = 0
  grad_w1 = x.T.dot(grad_h)

  # update weights of w1 and w2
  w1 -= learning_rate * grad_w1
  w2 -= learning_rate * grad_w2

### PyTorch: Tensors

这次我们使用PyTorch tensors来创建前向神经网络，计算损失，以及反向传播。

一个PyTorch Tensor很像一个numpy的ndarray。但是它和numpy ndarray最大的区别是，PyTorch Tensor可以在CPU或者GPU上运算。如果想要在GPU上运算，就需要把Tensor换成cuda类型。

In [2]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# randomly generate traning data
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

w1 = torch.randn(D_in, H)
w2 = torch.randn(H, D_out)

learning_rate = 1e-6
for it in range(500):
  #Forward pass
  h = x.mm(w1)  # N * H
  h_relu = h.clamp(min=0) # N * H
  y_pred = h_relu.mm(w2)   # N * D_out

  # compute loss
  loss = (y_pred - y).pow(2).sum().item()
  print(it, loss)

  # Backward pass
  #compute the gradient
  grad_y_pred = 2.0 * (y_pred - y)
  grad_w2 = h_relu.t().mm(grad_y_pred)
  grad_h_relu = grad_y_pred.mm(w2.t())
  grad_h = grad_h_relu.clone()
  grad_h[h<0] = 0
  grad_w1 = x.t().mm(grad_h)

  # update weights of w1 and w2
  w1 -= learning_rate * grad_w1
  w2 -= learning_rate * grad_w2

0 37940924.0
1 35675340.0
2 34338760.0
3 28782862.0
4 19994012.0
5 11567384.0
6 6201699.0
7 3429428.5
8 2123204.75
9 1480968.375
10 1129841.625
11 909993.5625
12 755895.5625
13 639122.125
14 546726.0
15 471690.46875
16 409633.6875
17 357626.125
18 313726.71875
19 276396.75
20 244440.65625
21 216987.75
22 193254.140625
23 172676.921875
24 154740.109375
25 139015.359375
26 125192.5625
27 112993.140625
28 102185.6875
29 92590.03125
30 84056.7890625
31 76442.6328125
32 69626.4609375
33 63510.6640625
34 58015.04296875
35 53064.68359375
36 48598.171875
37 44564.33203125
38 40912.484375
39 37597.8984375
40 34588.0
41 31850.296875
42 29353.31640625
43 27076.818359375
44 24998.853515625
45 23101.208984375
46 21364.55078125
47 19771.865234375
48 18311.341796875
49 16971.513671875
50 15739.810546875
51 14606.857421875
52 13564.1103515625
53 12603.357421875
54 11717.4921875
55 10903.2490234375
56 10153.2021484375
57 9460.9912109375
58 8821.3076171875
59 8228.65625
60 7679.5625
61 7170.6513671875
6

Easy to autograd

In [0]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

y = w*x + b # y = 2*1 + 3

y.backward()

# dy / dx = x
print(w.grad)
print(x.grad)
print(b.grad)

tensor(1.)
tensor(2.)
tensor(1.)


### Pytorch: Tensor and autograd

One important function of PyTorch is autograd, it can auto derivative all gradient of all parameters

One Tensor represents a node in computing graph. If `x` is a Tensor and `x.requires_grad=True`, `x.grad` 是另一个储存着x当前梯度（相当于一个scalar，常常是loss）的向量

In [0]:
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

w1 = torch.randn(D_in, H, requires_grad=True)
w2 = torch.randn(H, D_out, requires_grad=True)
y_pred = x.mm(w1).clamp(min=0).mm(w2)

# compute loss
loss = (y_pred - y).pow(2).sum()  # loss is a computation graph
print(it, loss)

# Backward pass
loss.backward()


499 tensor(28980630., grad_fn=<SumBackward0>)


In [0]:
w1.grad

tensor([[    43.2615,  14588.2188,  -3502.5093,  ...,    980.6359,
          -9134.0400,  -4731.7300],
        [ -5573.9766, -18620.1094,  -1356.8555,  ...,  -6540.2686,
         -32649.0195, -17386.9609],
        [ 35591.2227,  16292.5049,   9043.6992,  ...,  -1564.9768,
          33531.2695,  -1500.2920],
        ...,
        [ -1395.4663,  19331.9160,  -7150.3081,  ...,   -313.4011,
          -2732.7993,   1719.4480],
        [  1357.8234,   4822.6934,  -1309.7922,  ...,  -6154.7158,
          19664.8359,  11898.0098],
        [-11014.4873,  -1557.8982,  -4754.4780,  ...,   3842.9922,
          -2624.3643, -18650.4023]])

Only w1 and w2 have grad, x and y don't have grad

In [4]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# randomly generate traning data
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

w1 = torch.randn(D_in, H, requires_grad=True)
w2 = torch.randn(H, D_out, requires_grad=True)

learning_rate = 1e-6
for it in range(500):
  #Forward pass
  y_pred = x.mm(w1).clamp(min=0).mm(w2)

  # compute loss
  loss = (y_pred - y).pow(2).sum()  # loss is a computation graph
  print(it, loss.item())

  # Backward pass
  loss.backward()

  # update weights of w1 and w2
  with torch.no_grad(): # save memery, don't save w1.grad and w2.grad
    w1 -= learning_rate * w1.grad
    w2 -= learning_rate * w2.grad
    w1.grad.zero_() # if not, w1.grad will increase one time by one time
    w2.grad.zero_() 

0 24258520.0
1 17556780.0
2 15148436.0
3 14619362.0
4 14745759.0
5 14642763.0
6 13784261.0
7 11982024.0
8 9593092.0
9 7113953.0
10 4996418.0
11 3393298.5
12 2280177.5
13 1544165.875
14 1069187.125
15 763672.875
16 565269.25
17 433501.1875
18 343503.15625
19 279929.625
20 233411.734375
21 198181.15625
22 170690.125
23 148596.9375
24 130428.578125
25 115232.0703125
26 102371.8515625
27 91319.6796875
28 81743.5859375
29 73386.2578125
30 66054.625
31 59587.27734375
32 53858.96875
33 48776.78125
34 44252.48046875
35 40212.5078125
36 36595.21875
37 33347.359375
38 30425.978515625
39 27794.7265625
40 25418.818359375
41 23269.365234375
42 21323.68359375
43 19562.6640625
44 17963.8984375
45 16510.5
46 15187.060546875
47 13980.826171875
48 12878.6552734375
49 11873.0380859375
50 10953.84375
51 10112.9345703125
52 9342.61328125
53 8635.9296875
54 7987.54931640625
55 7391.9140625
56 6844.7060546875
57 6341.33544921875
58 5878.13525390625
59 5451.4375
60 5057.86083984375
61 4694.900390625
62 4359.9

### Pytorch: nn

这次我们使用Pytorch中的nn这个库来构造网络。用Pytorch autograd来构造计算图和计算gradient，然后pytorch会帮我们自动计算gradient

In [8]:
import torch.nn as nn

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# randomly generate traning data
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H, bias=False),  # w1 * x + b
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out)
)

#model = model.cuda()
torch.nn.init.normal_(model[0].weight)  # parameter change to normal distribution to get better results
torch.nn.init.normal_(model[2].weight)

loss_fn = nn.MSELoss(reduction='sum')

learning_rate = 1e-6
for it in range(500):
  #Forward pass
  y_pred = model(x)  # model.forward()

  # compute loss
  loss = loss_fn(y_pred, y)  # loss is a computation graph
  print(it, loss.item())



  # Backward pass
  loss.backward()

  # update weights of w1 and w2
  with torch.no_grad(): # save memery, don't save w1.grad and w2.grad
    for param in model.parameters():  # param (tensor, grad)
      param -= learning_rate * param.grad  # goal is minus grad from 
  model.zero_grad()

0 32281040.0
1 30272180.0
2 30909016.0
3 29217332.0
4 23486102.0
5 15600402.0
6 8979930.0
7 4884352.5
8 2769176.0
9 1729936.625
10 1202640.125
11 909722.5
12 727884.75
13 602774.375
14 509558.5625
15 436360.8125
16 376883.6875
17 327587.21875
18 286138.59375
19 250922.875
20 220814.515625
21 194960.953125
22 172631.859375
23 153274.015625
24 136429.359375
25 121737.046875
26 108874.859375
27 97577.265625
28 87615.46875
29 78824.90625
30 71043.078125
31 64129.078125
32 57977.84765625
33 52492.05859375
34 47593.33984375
35 43208.33203125
36 39273.19140625
37 35738.00390625
38 32556.74609375
39 29688.998046875
40 27101.224609375
41 24763.828125
42 22648.548828125
43 20732.099609375
44 18993.662109375
45 17414.900390625
46 15979.9892578125
47 14674.2685546875
48 13484.6298828125
49 12399.7236328125
50 11409.9599609375
51 10505.908203125
52 9679.75390625
53 8923.6611328125
54 8231.2763671875
55 7597.00244140625
56 7015.48095703125
57 6481.9658203125
58 5992.10498046875
59 5542.0732421875
60

In [7]:
model

Sequential(
  (0): Linear(in_features=1000, out_features=100, bias=False)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=10, bias=True)
)

### Pytorch: optim
这一次不再手动更新模型的weights，而是使用optim这个包来更新参数。optim这个package提供了各种不同的模型优化方法，包括SGD+momentum, RMSProp, Adam等

In [10]:
import torch.nn as nn

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# randomly generate traning data
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H, bias=False),  # w1 * x + b
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out)
)

#model = model.cuda()


loss_fn = nn.MSELoss(reduction='sum')
learning_rate = 1e-4 # For Adam, 1e-3 to 1e-4 
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

###############    For SGD optimizer  ########################
# torch.nn.init.normal_(model[0].weight)  # parameter change to normal distribution to get better results
# torch.nn.init.normal_(model[2].weight)
# learning_rate = 1e-6  
# optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
##############################################################

for it in range(500):
  #Forward pass
  y_pred = model(x)  # model.forward()

  # compute loss
  loss = loss_fn(y_pred, y)  # loss is a computation graph
  print(it, loss.item())

  optimizer.zero_grad()
  # Backward pass
  loss.backward()

  # update model parameters
  optimizer.step()


0 652.4390258789062
1 635.6054077148438
2 619.1981201171875
3 603.268798828125
4 587.7530517578125
5 572.6608276367188
6 557.8916015625
7 543.5771484375
8 529.65283203125
9 516.0699462890625
10 502.8695983886719
11 490.050048828125
12 477.6190185546875
13 465.5284729003906
14 453.7842102050781
15 442.4263000488281
16 431.4237365722656
17 420.75762939453125
18 410.3752746582031
19 400.2693786621094
20 390.490966796875
21 380.93060302734375
22 371.67095947265625
23 362.6505126953125
24 353.85882568359375
25 345.30914306640625
26 337.02716064453125
27 328.9324951171875
28 321.0216979980469
29 313.27545166015625
30 305.68231201171875
31 298.2498779296875
32 290.9680480957031
33 283.864990234375
34 276.943115234375
35 270.1908264160156
36 263.5945129394531
37 257.15625
38 250.85145568847656
39 244.6940155029297
40 238.66323852539062
41 232.7616729736328
42 226.9816131591797
43 221.30160522460938
44 215.7567596435547
45 210.33843994140625
46 205.037353515625
47 199.85313415527344
48 194.7809

### Pytorch: 自定义nn Modules

定义一个模型，这个模型继承自nn.Module类。如果需要定义一个比Sequential模型更加复杂的模型，就需要定义nn.Module模型

In [11]:
import torch.nn as nn

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# randomly generate traning data
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

class TwoLayerNet(torch.nn.Module):
  def __init__(self, D_in, H, D_out):
    super(TwoLayerNet, self).__init__()
    self.linear1 = torch.nn.Linear(D_in, H, bias=False)
    self.linear2 = torch.nn.Linear(H, D_out, bias=False)
  
  def forward(self, x):
    y_pred = self.linear2(self.linear1(x).clamp(min=0))
    return y_pred

model = TwoLayerNet(D_in, H, D_out)

#model = model.cuda()

loss_fn = nn.MSELoss(reduction='sum')
learning_rate = 1e-4 # For Adam, 1e-3 to 1e-4 
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

for it in range(500):
  #Forward pass
  y_pred = model(x)  # model.forward()

  # compute loss
  loss = loss_fn(y_pred, y)  # loss is a computation graph
  print(it, loss.item())

  optimizer.zero_grad()
  # Backward pass
  loss.backward()

  # update model parameters
  optimizer.step()

0 639.626220703125
1 623.183837890625
2 607.157958984375
3 591.58642578125
4 576.4970092773438
5 561.8151245117188
6 547.5734252929688
7 533.7909545898438
8 520.4666137695312
9 507.63165283203125
10 495.24151611328125
11 483.2508239746094
12 471.6859130859375
13 460.52008056640625
14 449.65966796875
15 439.13238525390625
16 428.91558837890625
17 418.9555969238281
18 409.2950439453125
19 399.8929748535156
20 390.734619140625
21 381.8029479980469
22 373.12005615234375
23 364.7010498046875
24 356.5187683105469
25 348.5360412597656
26 340.7286682128906
27 333.09027099609375
28 325.6412353515625
29 318.3617858886719
30 311.21832275390625
31 304.2663269042969
32 297.4598388671875
33 290.76763916015625
34 284.2041015625
35 277.802001953125
36 271.5396728515625
37 265.41552734375
38 259.42535400390625
39 253.5589141845703
40 247.837646484375
41 242.22256469726562
42 236.72103881835938
43 231.32748413085938
44 226.05633544921875
45 220.90721130371094
46 215.87155151367188
47 210.92385864257812
